server:
  port: 8082

spring:
  application:
    name: sentra-knowledge-service
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.107.15:5434/sentra_knowledge
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://admin:admin123@172.16.107.15:27017/sentra_doc?authSource=admin
    elasticsearch:
      uris: http://172.16.107.15:9200
  neo4j:
    uri: bolt://172.16.107.15:7687
    authentication:
      username: neo4j
      password: neo4j123
  rabbitmq:
    host: 172.16.107.15
    port: 5672
    username: admin
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

sentra:
  storage:
    graph-path: E:\项目备份\sentra\logs\sentra\graph
    sftp:
      host: 172.16.107.15
      port: 22
      username: 202312150002
      password: 20001017aA@
      upload-path: /data/lzm/sentra/data/files
      ocr-output-path: /data/lzm/sentra/data/ocr_result
  ocr:
    api-url: http://172.16.107.15:30000/file_parse
    backend: hybrid-auto-engine
    connect-timeout: 300000
    read-timeout: 1200000
  python:
    base-url: http://localhost:8000
