server:
  port: 8081

spring:
  application:
    name: sentra-user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.107.15:5434/sentra_user
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

sa-token:
  # 修改为与前端一致的 token 名称
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  # 改为 false，每次登录创建新 token
  is-share: false
  token-style: uuid
  is-read-body: false
  is-read-header: true
  # 允许 bearer 前缀
  is-bearer: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
